name: Trigger auto deployment for auth-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/auth-service-AutoDeployTrigger-df526f82-45f4-46af-9e7f-a3fb53ee550a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend/auth-service
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: shopx.azurecr.io
          registryUsername: ${{ secrets.AUTHSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTHSERVICE_REGISTRY_PASSWORD }}
          containerAppName: auth-service
          resourceGroup: shopx-u
          imageToBuild: shopx.azurecr.io/auth-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


